<Project>
    <PropertyGroup>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <GlobalPackageReference Include="DotNet.ReproducibleBuilds"
                                Version="2.0.5" />
        <GlobalPackageReference Include="Microsoft.Build.CopyOnWrite"
                                Version="1.0.334" />
    </ItemGroup>
</Project>
